---
config:
  - name: "foo"
    file: "zz_controller.go"
    path: "/internal/controller/null/resource/"
    time: "1"
  # - name: "bar"
  #   file: "bar.go"
  #   path: "home/to/path/bar"
  #   time: "2"
  # - name: "baz"
  #   file: "baz.go"
  #   path: "home/foo/baz.go"
  #   time: "3"

